name: Latest Blog Post Workflow
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: List Files (Debug)
        run: ls -R
        
      - name: Update README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.xbstack.com/rss.xml"
          readme_path: "./profile/README.md"
          max_post_count: 5
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "chore: 同步最新文章到 Profile"
